apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-first
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-first
  template:
    metadata:
      labels:
        app: go-first
    spec:
      containers:
        - name: go-first-container
          image: docker.io/itechzero/go-first:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-first
  labels:
    app: go-first
spec:
  selector:
    app: go-first
  ports:
    - name: go-first
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31080
  type: NodePort